server:
  port: 8083

spring:
  docker:
    compose:
      file: ../docker-compose.yml
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: officeRoutes
    consumer:
      group-id: OfficeGroupId
      auto-offset-reset: latest

application:
  ports:
    - name: "Port 1"
      x: 10
      y: 20
    - name: "Port 2"
      x: 70
      y: 80
    - name: "Port 3"
      x: 50
      y: 80